"""Add clerk id users table

Revision ID: 60e60d7325b1
Revises: 872b0e5a2980
Create Date: 2025-02-11 23:53:30.207196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e60d7325b1'
down_revision: Union[str, None] = '872b0e5a2980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['clerk_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###
