"""Fix relationships

Revision ID: 872b0e5a2980
Revises: db5cf6e8c617
Create Date: 2025-02-11 12:10:41.931221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872b0e5a2980'
down_revision: Union[str, None] = 'db5cf6e8c617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
